/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Character2(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/Character2Talking-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions.talk.play();
  }, []);
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      position={[10, 0, 1.5]}
      rotation={[0, Math.PI, 0]}
    >
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="Ch21_Body"
            geometry={nodes.Ch21_Body.geometry}
            material={materials.Ch21_body}
            skeleton={nodes.Ch21_Body.skeleton}
          />
          <skinnedMesh
            name="Ch21_Eyelasshes"
            geometry={nodes.Ch21_Eyelasshes.geometry}
            material={materials.Ch21_hair}
            skeleton={nodes.Ch21_Eyelasshes.skeleton}
          />
          <skinnedMesh
            name="Ch21_Hair"
            geometry={nodes.Ch21_Hair.geometry}
            material={materials.Ch21_hair}
            skeleton={nodes.Ch21_Hair.skeleton}
          />
          <skinnedMesh
            name="Ch21_Pants"
            geometry={nodes.Ch21_Pants.geometry}
            material={materials.Ch21_body}
            skeleton={nodes.Ch21_Pants.skeleton}
          />
          <skinnedMesh
            name="Ch21_Shirt"
            geometry={nodes.Ch21_Shirt.geometry}
            material={materials.Ch21_body}
            skeleton={nodes.Ch21_Shirt.skeleton}
          />
          <skinnedMesh
            name="Ch21_Shoes"
            geometry={nodes.Ch21_Shoes.geometry}
            material={materials.Ch21_body}
            skeleton={nodes.Ch21_Shoes.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Character2Talking-transformed.glb");
