/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Character3(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/Character3Talking-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions.talk.play();
  }, []);
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      position={[9.3, 0, 1.5]}
      rotation={[0, Math.PI, 0]}
    >
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="Ch13_Body"
            geometry={nodes.Ch13_Body.geometry}
            material={materials.Ch13_body}
            skeleton={nodes.Ch13_Body.skeleton}
          />
          <skinnedMesh
            name="Ch13_Eyeleashes"
            geometry={nodes.Ch13_Eyeleashes.geometry}
            material={materials.Ch13_hair}
            skeleton={nodes.Ch13_Eyeleashes.skeleton}
          />
          <skinnedMesh
            name="Ch13_Hair"
            geometry={nodes.Ch13_Hair.geometry}
            material={materials.Ch13_hair}
            skeleton={nodes.Ch13_Hair.skeleton}
          />
          <skinnedMesh
            name="Ch13_Pants"
            geometry={nodes.Ch13_Pants.geometry}
            material={materials.Ch13_body}
            skeleton={nodes.Ch13_Pants.skeleton}
          />
          <skinnedMesh
            name="Ch13_Shirt"
            geometry={nodes.Ch13_Shirt.geometry}
            material={materials.Ch13_body}
            skeleton={nodes.Ch13_Shirt.skeleton}
          />
          <skinnedMesh
            name="Ch13_Shoe"
            geometry={nodes.Ch13_Shoe.geometry}
            material={materials.Ch13_body}
            skeleton={nodes.Ch13_Shoe.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Character3Talking-transformed.glb");
