/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: maplol123 (https://sketchfab.com/maplol123)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/earth-low-poly-6df66a991b4a42379d078e3dae69d593
title: Earth low poly
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { Clock, Vector3 } from "three";

export function Earth({ scroll, ...props }) {
  const { nodes, materials } = useGLTF("/earth_low_poly-transformed.glb");
  const earth = useRef();
  const clock = new Clock();
  const { camera } = useThree();
  const newPos = new Vector3(4, 3, 5);
  const lookAtLerp = new Vector3();
  const lookAtVector = new Vector3(4, 1.7, 2);
  useFrame((state, delta) => {
    if (earth.current) {
      earth.current.rotation.z -= delta * 0.2;
      if (scroll) {
        camera.position.lerp(newPos, 0.006);
        const lookAt = lookAtLerp.lerp(lookAtLerp, 0.006);
        camera.lookAt(lookAt);
      }
    }
  });

  return (
    <group
      {...props}
      dispose={null}
      scale={0.4}
      ref={earth}
      rotation={[0, 0.8, 0]}
      position={[4, -1, 0]}
      receiveShadow
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 0.02]}>
            <mesh
              geometry={nodes.Object_5.geometry}
              material={materials[".007"]}
            />
          </group>
          <group position={[0, 0, 0.02]}>
            <mesh
              geometry={nodes.Object_7.geometry}
              material={materials[".008"]}
            />
          </group>
          <mesh
            geometry={nodes.Object_9.geometry}
            material={materials[".004"]}
          />
          <group position={[-0.09, 0, 0]}>
            <mesh
              geometry={nodes.Object_11.geometry}
              material={materials[".003"]}
            />
          </group>
          <mesh
            geometry={nodes.Object_13.geometry}
            material={materials[".006"]}
          />
          <mesh
            geometry={nodes.Object_15.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.Object_17.geometry}
            material={materials[".005"]}
          />
          <mesh
            geometry={nodes.Object_19.geometry}
            material={materials[".009"]}
          />
          <mesh
            geometry={nodes.Object_21.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.Object_23.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.Object_25.geometry}
            material={materials.material}
          />
          <group scale={8.49}>
            <mesh
              geometry={nodes.Object_27.geometry}
              material={materials[".002"]}
            />
          </group>
          <group rotation={[-0.02, -0.01, 0]}>
            <group
              position={[-8.37, 1.09, 4.36]}
              rotation={[0.95, -0.03, -0.86]}
              scale={[-0.58, 0.55, 0.51]}
            >
              <mesh
                geometry={nodes.Object_30.geometry}
                material={materials.material_0}
              />
            </group>
            <group
              position={[8.9, -1.68, -3.4]}
              rotation={[2.01, -0.05, 2.48]}
              scale={[-0.55, 0.58, 0.54]}
            >
              <mesh
                geometry={nodes.Object_32.geometry}
                material={materials.material_0}
              />
            </group>
            <group
              position={[0.61, 4.24, -8.91]}
              rotation={[-Math.PI, 0.08, -Math.PI]}
              scale={0.87}
            >
              <mesh
                geometry={nodes.Object_34.geometry}
                material={materials.material_0}
              />
            </group>
            <group
              position={[6.43, 3.01, 6.93]}
              rotation={[0.02, 1.01, 0]}
              scale={0.74}
            >
              <mesh
                geometry={nodes.Object_36.geometry}
                material={materials.material_0}
              />
            </group>
            <group
              position={[-7.73, -4.89, -4.39]}
              rotation={[0.14, -0.86, 0.4]}
              scale={0.98}
            >
              <mesh
                geometry={nodes.Object_38.geometry}
                material={materials.material_0}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/earth_low_poly-transformed.glb");
